### ISSUE TITLE
Argument help doesn't work on Excel 2010 / Windows 7

### ISSUE THREAD

**Issue by govert** [Excel-DNA/IntelliSense#1]
On an Excel 2010 / Windows 7 machine, the argument help does not appear. This seems to be due to the TextPattern not being supported by the edit controls on that combination. The relevant part of the code is in the FormulaEditWatcher.UpdateActivePattern() in Watchers.cs.

A partial workaround would be to use the legacy Value pattern, though we would not be able to track the current insertion point that way.

This needs further investigation - there are different approaches to the UI Automation which do different mappings of controls information to the UI Automation patterns. Although the Inspect tool run on Windows 7 indicates that even Notepad does not support the TextPattern, a simple application that interacts with Notepad does find support for the TextPattern. Does this also apply to the Excel edit controls.

**Comment by garethhayter** [comment]
Using the latest code from GitHub, I still don't get argument help on Excel 2013 32bit, Windows 8.1 64bit. I do get function help, just not argument help, which is probably even more useful than the function help. Any further progress?

**Comment by govert** [comment]
The IntelliSense extension works on Windows 7 / Excel 2010 now.
