### ISSUE TITLE
ElementNotAvailable exception when exiting Excel

### ISSUE THREAD

**Issue by bevanweiss** [Excel-DNA/IntelliSense#10]
I get the following exception:
An exception of type 'System.Windows.Automation.ElementNotAvailableException' occurred in UIAutomationClient.dll but was not handled in user code
Additional information: Unrecognized error.
This was raised on line 248 of Watchers.cs when exiting Excel.
This is on Windows 7 32-bit with Excel 2013.

I suspect that although the value of windowWatcher.mainWindow (a persisted handle I presume) was not zero that the actual main window handle was not valid as the Excel window was closed at the time.

**Comment by govert** [comment]
This is from a very old version, and should be fixed by now.
Please reopen if the problem persists.
