### ISSUE TITLE
Fix for 'Unexpected DESTROY of PopupListWindow'

### ISSUE THREAD

**Issue by garethhayter** [Excel-DNA/IntelliSense#11]
I get an 'Unexpected DESTROY of PopupListWindow' message when Excel is closed while in edit-mode.

I made these changes to IntellisenseHelper.cs fix it:

1) Make uiMonitor a class field.
2) Change the Dispose method to this:

public void Dispose()
{
	if (_id != null)
		_id.Dispose();

	if (uiMonitor != null)
		uiMonitor.Dispose();
}

Then I call Dispose explicitly when exiting edit-mode.

**Comment by govert** [comment]
Can you describe the steps to reproduce the error?

**Comment by govert** [comment]
Should the `UIMonitor.Dispose()` call not be in the `IntelliSenseDisplay`?
`IntelliSenseHelper` still needs to be revisited.

**Comment by garethhayter** [comment]
govert: I'm using the library to hook the formula editor events and get the current text, caret position etc, not for displaying IntelliSense. I don't use the library in the normal way: I create an instance of IntelliSenseHelper when Excel enters edit-mode, then dispose it when Excel exits edit-mode.

The problem is that when I call Dispose() directly, uiMonitor doesn't get disposed and the reported exception gets thrown.

**Comment by govert** [comment]
This should be fixed now - I've added the `UIMonitor.Dispose()` call in the `IntelliSenseDisplay`.
