### ISSUE TITLE
XML Schema not available (any more?)

### ISSUE THREAD

**Issue by Mo-Gul** [Excel-DNA/IntelliSense#116]
I am not totally sure how this stuff normally works, but shouldn't the link given in the XML example files, e.g.

https://github.com/Excel-DNA/IntelliSense/blob/7b936b9df7f40b17025cd227c5e4d647f5a27080/VBASamples/VBAFunctions.CustomXMLPart.xml#L1

be available/working? (Maybe the schema has moved somewhere else and you missed to update the XML files?)

---
_Background is that I am trying to create an XSD file to ensure that the XML file is properly formatted and e.g. strings are not longer than 255 characters. My goal is to use the XML file to use it for IntelliSense as well as to use it to register the functions (i.e. use the content of the XML file for `Application.MacroOptions`)._

_Of course I am willing to share the result and maybe you can incorporate it here or at least link to it, if it will not be incorporated here._

**Comment by bevanweiss** [comment]
No.
The namespace only has to be unique, which is why a standard URI style format is used.
The URI itself does not need to exist, it should never be looked up by any XML parser.  It is just a unique key.

**Comment by Mo-Gul** [comment]
Thank you for the clarification.
