### ISSUE TITLE
Quotation mark behavior not like Excel

### ISSUE THREAD

**Issue by FrankHalbach** [Excel-DNA/IntelliSense#16]
I notice that the intellisense display is jumping to the next argument when I enter quotation marks and comma, e.g.=myUDF("some text, some more text",arg2). If you click on some more text, the intellisense display show jumps to arg2.

I guess the Excel like behavior is that it doesn't move to the next the argument until the quotation marks are closed

Frank

**Comment by govert** [comment]
This is due to the simplistic formula parsing - issue #12 explains what we need to do in a bit more detail.

**Comment by Ron-Ldn** [comment]
There is a corner case not treated in the algorithm I checked-in: when the cursor is inside a text. Ex: 
`=myUDF("some text, some`

In order not to rewrite the whole algorithm, I came with a simple workaround: count the number of double-quotes. If that number is odd, then manually insert a double-quotes in the end of the string before applying all the regular expressions. It works on my local.

**Comment by FrankHalbach** [comment]
I was just testing a bit more and figured that if you start a formula with + or - the intelli display is not showing up.
