### ISSUE TITLE
Argument details not showing when user clicked on the proposed function

### ISSUE THREAD

**Issue by Ron-Ldn** [Excel-DNA/IntelliSense#17]
Let's say I have a function AddThem(v1, v2). If I start typing "=AddT" then I get the suggestion "AddThem". If I click on the suggestion, then my function call will be completed to "=AddThem(" and the cursor will be positioned after the parenthesis. But then no intellisense will appear, while I would expect getting the parameter list. If I enter a character then the intellisense comes back.
Excel handles this use-case properly with native functions. I assume that there is an event to subscribe to in order to be notified when the function is inserted.

**Comment by govert** [comment]
I will take a look at this issue first.

**Comment by govert** [comment]
I've pushed a fix for this.

**Comment by Ron-Ldn** [comment]
It works perfectly now.
