### ISSUE TITLE
Refresh function list when add-in calls ExcelIntegration.RegisterMethods

### ISSUE THREAD

**Issue by Ron-Ldn** [Excel-DNA/IntelliSense#18]
If the add-in explicitly calls ExcelIntegration.RegisterMethods after IntelliSenseServer.Register then the newly registered functions are not taken into account by the display server.

**Comment by govert** [comment]
I've pushed an update that adds `IntelliSenseServer.Refresh()` but not tested it yet.

**Comment by govert** [comment]
This should be fine now.
Please re-open if there are any problems with the `Refresh()`.

**Comment by Ron-Ldn** [comment]
I confirm this works.
