### ISSUE TITLE
Function overlap

### ISSUE THREAD

**Issue by Ron-Ldn** [Excel-DNA/IntelliSense#19]
What if the developer creates a UDF whose name is already used by Excel? For example, if I create a function "SUM" with ExcelDNA, I see that when I call it, this is actually the native Excel SUM which is used, but the IntelliSense is still there.

![functionoverlap](https://cloud.githubusercontent.com/assets/9251708/16297093/3135be7e-3927-11e6-9986-ba6c695568ef.png)

This is a true corner case. Perhaps the new function should be filtered at the ExcelDNA level. In fact, Excel itself proposes 2 functions in its IntelliSense.

![functionoverlap2](https://cloud.githubusercontent.com/assets/9251708/16297153/78d7ea9a-3927-11e6-9b74-667d244f3a3c.png)

**Comment by govert** [comment]
I hadn't noticed this before. I'd think of it as an Excel-DNA issue, rather than with the IntelliSense itself. Excel-DNA thinks the new name SUM has been registered, as does Excel itself (by showing it in the list twice).
Excel-DNA might keep lists of the built-in functions, but what about localized languages. Otherwise we can Evaluate the names when registering, and give an error or warning when overwriting.
Not something I think is too serious though.

**Comment by govert** [comment]
@Ron-Ldn I've made some improvements on the Excel tooltip overlap in the latest release - https://github.com/Excel-DNA/IntelliSense/releases/tag/v0.1.4-beta2 . It's really tricky to track Excel's tooltips (there are different ones showing and hidden at weird times).

For now I hide the Excel tool tip when ours is shown, but more typing can show Excel's tool tip again, which I don't suppress yet.

**Comment by Ron-Ldn** [comment]
I see the 2 pop-ups but indeed they are not overlapping. In my opinion, this is the most important. I even think that you should not hide the Excel one because there is an ambiguity regarding the function and it makes sense to tell the user that he or her cannot be sure what function will be called in the end.

![sumclash](https://cloud.githubusercontent.com/assets/9251708/17330738/db4f5804-58bf-11e6-9fab-9e261b13cd7c.png)

In my example, when I called "SUM(2,5)" this is actually the native one which was called, not mine.

In my opinion, the behaviour of the latest version of ExcelDna IntelliSense is good and I can close the case. Do you agree or do you want me to keep it open?

**Comment by govert** [comment]
I'll close this one, but keep the original #15.
