### ISSUE TITLE
Multiple add-ins using IntelliSense

### ISSUE THREAD

**Issue by govert** [Excel-DNA/IntelliSense#2]
I'm quite concerned about people distributing add-ins with the feature included. That would break it for other add-ins trying to do the same. So either it must be a standalone add-in, or there must be some mechanism to have only one 'active' instance.

I'd prefer to make it so that the ExcelDna.IntelliSense add-in is alone-standing, but there should probably also be a mechanism to allow an add-in to incorporate the code. For this there must be a mechanism to ensure only one add-in is actively providing the IntelliSense services (hopefully to any other Excel-DNA add-ins that might be installed too). But at the very least there must be a lock of some sort (maybe a named Mutex) to ensure that multiple add-ins with the code can still run.

Excel-DNA now (v 0.32) has a mechanism to query for all registered functions and their registration details. That should be used by the one IntelliSense provider to do IntelliSense for all the add-ins.

**Comment by Ron-Ldn** [comment]
Hi Govert,

I am trying to update ExcelDna to 0.32 in the IntelliSense projet, and I am struggling with that ExcelIntegration.GetRegistrationInfo function. 

I see it needs a version number, and I have no idea where to get it from. This number is generated by the ExcelDna.Loader when the add-in is registered, then it depends on the number of add-ins (and also the number of manual registrations made by the add-ins). 
Any idea ?

**Comment by govert** [comment]
The real code for the GetRegistrationInfo is in ExcelDna.Loader\XlRegistration.cs.

The version is a performance optimization to allow efficient polling - initially the version is 0.0, and it is incremented any time the registration info for the add-in changes. If you pass in the current version, the function will just return null, so the whole registration block is not marshalled on every call.

If you just pass in -1, it should return the whole array every time.

Let me know if I need to take a closer look.

**Comment by govert** [comment]
Here's a .dna file that might still work:

```xml
<DnaLibrary RuntimeVersion="v4.0" Language="VisualBasic">
<Reference Name="Microsoft.Office.Interop.Excel" />
<![CDATA[

Imports Microsoft.Office.Interop.Excel

Public Module TestRegistrationInfo

    <ExcelCommand(MenuName:="Excel-DNA", MenuText:="Registration Info Dump")>
    Sub RegistrationInfo()
        Try
            Dim Application As Application = ExcelDnaUtil.Application
            Dim addinPaths As IEnumerable(Of String)

            If ExcelDnaUtil.ExcelVersion >= 14.0 Then
                addinPaths = From addIn As AddIn In Application.AddIns2
                             Where addIn.IsOpen
                             Select addIn.FullName
            Else
                Dim allPaths As New HashSet(Of String)
                Dim funcInfos As Object = Application.RegisteredFunctions

                If Not funcInfos Is Nothing Then
                    For i As Integer = LBound(funcInfos) to UBound(funcInfos)
                        allPaths.Add(funcInfos(i, 1))
                    Next
                End If
                addinPaths = allPaths
            End If

            Dim wb = Application.Workbooks.Add()
            Dim shIndex As Worksheet= wb.Sheets(1)
            shIndex.Name = "Add-Ins"
            shIndex.Cells(1, 1) = "Add-In Path"
            shIndex.Cells(1, 2) = "Registration Info?"

            Dim row As Integer = 2
            For Each path As String In addinPaths
                shIndex.Cells(row, 1) = path

                ' Try to read RegistrationInfo
                Dim result = ExcelIntegration.GetRegistrationInfo(path, 0)
                If result.Equals(ExcelError.ExcelErrorNA) Then
                    shIndex.Cells(row, 2) = False
                Else
                    shIndex.Cells(row, 2) = True

                    ' Dump the result to a new sheet
                    Dim shInfo As Worksheet = wb.Sheets.Add(After:=wb.Sheets(wb.Sheets.Count))
                    shInfo.Name = System.IO.Path.GetFileName(path)

                    ' C API via ExcelReference would work well here
                    Dim refInfo = New ExcelReference(0, UBound(result), 0, 254, shInfo.Name)
                    refInfo.SetValue(result)

                End If

                row = row + 1
            Next
            shIndex.Activate()

        Catch ex As Exception
            Debug.Print(ex.ToString())
        End Try
    End Sub

    End Module
]]>

</DnaLibrary>

**Comment by Ron-Ldn** [comment]
Indeed, it works fine with "-1". 
I managed to make it work with this quick and dirty code :

void RegisterIntellisense()
        {
            object[,] regInfos = ExcelIntegration.GetRegistrationInfo(Win32Helper.GetXllName(), -1) as object[,];

            if (regInfos != null)
            {
                for (int i = 0; i < regInfos.GetLength(0); i++)
                {
                    if (regInfos[i, 0] is ExcelDna.Integration.ExcelEmpty)
                    {
                        string functionName = regInfos[i, 3] as string;
                        string description = regInfos[i, 9] as string;

                        string argumentStr = regInfos[i, 4] as string;
                        string[] argumentNames = argumentStr == null ? new string[0] : argumentStr.Split(',');

                        List<IntelliSenseFunctionInfo.ArgumentInfo> argumentInfos = new List<IntelliSenseFunctionInfo.ArgumentInfo>();
                        for (int j = 0; j < argumentNames.Length; j++)
                        {
                            argumentInfos.Add(new IntelliSenseFunctionInfo.ArgumentInfo { ArgumentName = argumentNames[j], Description = regInfos[i, j+10] as string });
                        }

                        _id.RegisterFunctionInfo(new IntelliSenseFunctionInfo
                        {
                            FunctionName = functionName,
                            Description = description,
                            ArgumentList = argumentInfos
                        });
                    }
                }
            }
        }

**Comment by Ron-Ldn** [comment]
Do you see any issue with this ?
If you are happy, then I will polish a bit, test it more, and finally commit ExcelDna 0.32.

**Comment by Ron-Ldn** [comment]
I have checked-in my changes. Unfortunately, I cannot install Git on the machine where I am working now. Then I don't know how I can upload ExcelDna.Integration.dll 0.32 and the corresponding ExcelDna.IntelliSense.xll.
If you have time, perhaps you can do it for me ?
Otherwise I will do later.

There are still some bugs which I am investigating on, but at least I am able to have one instance of the intellisense for the both add-ins, using ExcelDna 0.32.

**Comment by govert** [comment]
OK - I still think it's more complicated not having a standalone add-in, but I think we can figure it out.
My current suggestion is something like this:
_I don't mean for all of this to be done now, just to start a more detailed discussion._

### IntelliSense Providers
An add-in that provides registration information for UDF functions to the IntelliSense mechanism is an "IntelliSense Provider". All Excel-DNA add-ins since v 0.32 are IntelliSense Providers through the GetFunctionRegistrationInfo() feature. In future we might make some mechanisms for other IntelliSense Providers, for example:
* a mechanism for regular VBA add-ins
* xml or other mark-up files that describe the extra function info, so that any add-in (non Excel-DNA) can use the IntelliSense feature.

We'll need to decide how IntelliSense Providers can provide enhanced information beyond the current function and argument descriptions, e.g. enum lists or hyperlinks, but details of that can come later.

### IntelliSense Servers
An add-in that is able to perform the IntelliSense display is an "IntelliSense Server".
We move from having ExceDna.IntelliSense.xll as an add-in, to ExcelDna.IntelliSense.dll which is the library to be included in any IntelliSense Server.

An Excel process can have only one IntelliSense Server as the "Active IntelliSense Server". This is the add-in that is actively hooked into the UI Automation, popping up the windows etc. We implement it so that the Active IntelliSense Server is always the one with the newest version. So suppose an IntelliSense Server add-in loads and becomes the Active one. Then later an add-in with a newer version IntelliSense server is loaded. This add-in must now tell the Active IntelliSense Server to deactivate, and itself then become the Active Server.

So the rule is that the Active IntelliSense Server is always one of those with the latest version among the IntelliSense Servers loaded in the process.

Further, we ensure there is a deactivation process, so that if an add-in that is the Active IntelliSense Server is unloaded, there is a way (some arbitrary choice) to Activate one of the latest-version IntelliSense Servers among those loaded.

### Disable (enable) switch
We need to have a master-switch (a registry entry or something) that completely disables IntelliSense. It must be easy (or at least possible) to use add-ins that are IntelliSense Servers without having the IntelliSense part operating. Otherwise, an add-in that is an IntelliSense Server is useless if the IntelliSense doesn't work well on a particular environment.
For now, maybe it should even be opt-in as a safety measure.

**Comment by govert** [comment]
I moved the ideas to an [Architecture wiki page](https://github.com/Excel-DNA/IntelliSense/wiki/Architecture), and started adding some details before I give implementation a try.

**Comment by govert** [comment]
This is now implemented.
