### ISSUE TITLE
Using binary ExcelDna.Intellisense.xll displays 'Error trying to run SyncMacro'

### ISSUE THREAD

**Issue by terryaney** [Excel-DNA/IntelliSense#20]
Doesn't seem to be affecting me in any way that I know, but when I use the *.xll display host, every time I shut down Excel, DebugView displays:

[34972] Error trying to run SyncMacro - Excel is shutting down. Queued macro execution abandoned. : InvalidOperationException - LPenHelper call failed. Excel is shutting down. 

Just thought I'd let you know.

**Comment by govert** [comment]
Is this only under the Debug version? If so, I think it's harmless.

**Comment by terryaney** [comment]
No, just tested in release mode and got these two messages.

[2184] ExcelDna.Integration Error: 6 : 
[2184] Error trying to run SyncMacro - Excel is shutting down. Queued macro execution abandoned. : InvalidOperationException - LPenHelper call failed. Excel is shutting down.

**Comment by govert** [comment]
This error is shown by the Excel-DNA side, though the call probably originates in the IntelliSense extension. I've already changed the logging from an Error to a Warning in February, so it should not pop up in the next Excel-DNA version.

I'm not sure whether I can prevent it from the IntelliSense side, where I try to stop everything as quickly as possible when the process exits. I'll have to check this again.

**Comment by govert** [comment]
Please check the latest release - https://github.com/Excel-DNA/IntelliSense/releases/tag/v0.1.4-beta2 - for this issue. It might be fixed now...

**Comment by terryaney** [comment]
Attached debug view.  I just opened and closed excel.  Line 361/362 still show error happening.

Interesting too (might want me to document on another issue), line 60 is showing my sample function description from Xml file, but when I type the function in Excel, the intellisense is still coming from the [ExcelFunction] attribute.

Thanks for the update.  Let me know if you want me to try anything else.

[
[trace.txt](https://github.com/Excel-DNA/IntelliSense/files/370065/trace.txt)
](url)

**Comment by govert** [comment]
Thanks for the feedback.

OK - then I haven't fix the error popup yet.
It doesn't happen on my machine (but at least one other user) so it tricky to track down.

The xml story hasn't changed yet - the previous version was also loading the xml file, but the [ExcelFunction] version always 'wins'. I need some plan for merging them, or at least having the xml version win. There's some issue with the timing when they load, but not a big problem.

-Govert


On 18 Jul 2016, at 22:31, Terry Aney <notifications@github.com<mailto:notifications@github.com>> wrote:


Attached debug view. I just opened and closed excel. Line 361/362 still show error happening.

Interesting too (might want me to document on another issue), line 60 is showing my sample function description from Xml file, but when I type the function in Excel, the intellisense is still coming from the [ExcelFunction] attribute.

Thanks for the update. Let me know if you want me to try anything else.


<url>trace.txt<https://github.com/Excel-DNA/IntelliSense/files/370065/trace.txt>

**Comment by govert** [comment]
@terryaney I've made another small attempt to catch this error pop-up.

Could you please report whether the error po-up still happens with release https://github.com/Excel-DNA/IntelliSense/releases/tag/v0.1.5-beta3 ?

If it does, could you perhaps add the ExcelDna,.IntelliSense.config file, set the logging level to `switchValue="All"` and post the last few entries of the log?

**Comment by terryaney** [comment]
@govert Still getting the dialog.  And when I say dialog, you realize that a) It is your ExcelDNA LogDisplay and b) It is only there for a second, then automatically closes.  It is not a blocking dialog.

Anyway, I copied a .config out there, but seem to be getting same messages.  I've attached entire trace (instead of last few lines).  Do you think my .config isn't kicking in? (I just took the one from the site so assume no typos or anything in it?)
[trace.txt](https://github.com/Excel-DNA/IntelliSense/files/393971/trace.txt)

**Comment by govert** [comment]
Thank - it doesn't look quite right - I'll check the .config again and let you know if I can make a better trace.

It seems like the error is not actually coming from the IntelliSense side, but comes from an `ExcelAsyncUtil.QueueAsMacro` that tries to run after the shutdown. There are some ways to improve the handling of this on the `ExcelDna.Integration` core add-in library.

So I'm a bit surprised it surfaces only when you run the IntelliSense.

**Comment by terryaney** [comment]
Just confirmed again (in case I was making a mistake), and to your surprise ;) It is true.  Without intellisense, there is no dialog and nothing in debug view trace.

**Comment by govert** [comment]
@terryaney What Excel version are you running?

**Comment by terryaney** [comment]
Home and Student 2013.  v 15.0.4841.1002.

**Comment by govert** [comment]
This should be fixed with commit 1b81904cb924cedd453fc28d8c69dc37678be158
