### ISSUE TITLE
Able to show full parameter list and descriptions

### ISSUE THREAD

**Issue by terryaney** [Excel-DNA/IntelliSense#21]
As you are probably aware, the Excel function dialog does some weird things if you have long descriptions and/or lots of parameters.  Looks like intellisense behaves same way, probably by design, but wondering if any options for you to pull parameters and attribute descriptions yourself?  Or are the mistakes already 'compiled' into xll before you even start to pull intellisense.

Just 'struggling' with decision of where to put documentation.  C# code, external document, or Excel attributes - and not really wanting to duplicate documentation ;)

Thanks in advance.

**Comment by Ron-Ldn** [comment]
I can see that the closing parenthesis is always at the end of the first row, even if there are multiple rows for the arguments. Is that what you are referring to, or did you notice any other issues?

**Comment by Ron-Ldn** [comment]
Ok I found another issue: the arguments are always inserted in the first row, and so the last ones can be squeezed vertically, which is not aesthetic.

![displayissue](https://cloud.githubusercontent.com/assets/9251708/16373271/4f6a063c-3c49-11e6-9de0-0c7c4e439204.png)

**Comment by terryaney** [comment]
No, that wasn't what I was referring to.  Given this 'monster' of a function:

        [ExcelFunction( Category = "Financial", Description = "Returns 401k contributions/match." )]
        public static double[] BTRGetContributions(
            [ExcelArgument( "Required.  The MatchType to use for calculations.  MultiplierBasedOnPercent = 1, MultiplierBasedOnDollars = 2, ERMatchPercentBasedOnPercent = 3, ERMatchDollarsBasedOnDollars = 4." )]
            int matchType,
            [ExcelArgument( "Required.  Whether to credit true-up math at the end of the year when employee hits contribution limit." )]
            bool isTrueup,
            [ExcelArgument( "Required.  Whether to provide match on catch-up contributions." )]
            bool isCatchupMatch,
            [ExcelArgument( "Required.  Whether to allow pre-tax contributions over limit to overflow to after-tax contributions." )]
            bool isPretaxOverflowToAftertax,
            [ExcelArgument( "Required.  Whether to provide match on after-tax contributions." )]
            bool isAftertaxMatch,
            [ExcelArgument( "Required.  | delimited list of periods.  Each period is in the form of M:P:P where M is number of months for this period, and each P is a tier of a , seperated pair of decimal values." )]
            string matchParam,
            [ExcelArgument( "Required.  The ContributionType to use for calculations.  PercentBasedOnAge = 1, PercentBasedOnService = 2, PercentBasedOnAgePlusService = 3." )]
            int contributionType,
            [ExcelArgument( "Required.  Contribution parameters.  See matchParm for info." )]
            string contributionParam,
            [ExcelArgument( "Required.  Calculation year." )]
            int year,
            [ExcelArgument( "Required.  Calculate contributions as of the end of this month." )]
            double monthEnd,
            [ExcelArgument( "Required.  Number of Pay period in a year." )]
            int payPeriod,
            [ExcelArgument( "Required.  Annual Pay rate as of start pay period." )]
            double rateOfPay,
            [ExcelArgument( "Required.  Pay period when pay increases." )]
            int payPeriodWhenPayIncreases,
            [ExcelArgument( "Required.  Pay increase rate." )]
            double ratePayIncrease,
            [ExcelArgument( "Required.  Inflation rate (used to project limits)." )]
            double rateOfInflation,
            [ExcelArgument( "Required.  Investment rate of return." )]
            double rateOfReturn,
            [ExcelArgument( "Optional.  Pre-tax contribution as a % of pay." )]
            double pretaxPct = 0d,
            [ExcelArgument( "Optional.  Flat $ pre-tax contribution amount per pay period." )]
            double pretaxFlatPerPayPeriod = 0d,
            [ExcelArgument( "Optional.  Roth contribution as a % of pay." )]
            double rothPct = 0d,
            [ExcelArgument( "Optional.  Flat $ Roth contribution amount per pay period." )]
            double rothFlatPerPayPeriod = 0d,
            [ExcelArgument( "Optional.  After-tax contribution as a % of pay." )]
            double aftertaxPct = 0d,
            [ExcelArgument( "Optional.  Flat $ after-tax contribution amount per pay period." )]
            double aftertaxFlatPerPayPeriod = 0d,
            [ExcelArgument( "Optional.  Starting Pay period.  Defaults to 1." )]
            object startPayPeriodArg = null,
            [ExcelArgument( "Optional.  YTD savings pay." )]
            double ytdPay = 0d,
            [ExcelArgument( "Optional.  YTD pre-tax contributions." )]
            double ytdPretax = 0d,
            [ExcelArgument( "Optional.  YTD Roth contributions." )]
            double ytdRoth = 0d,
            [ExcelArgument( "Optional.  YTD after-tax contributions." )]
            double ytdAftertax = 0d,
            [ExcelArgument( "Optional.  YTD pre-tax catch-up contributions." )]
            double ytdPretaxCatchup = 0d,
            [ExcelArgument( "Optional.  YTD Roth catch-up contributions." )]
            double ytdRothCatchup = 0d,
            [ExcelArgument( "Optional.  YTD employer match contributions." )]
            double ytdERMatch = 0d,
            [ExcelArgument( "Optional.  YTD employer contributions." )]
            double ytdERCont = 0d,
            [ExcelArgument( "Optional.  Age at BOY." )]
            double ageBOY = 0d,
            [ExcelArgument( "Optional.  Service at BOY." )]
            double svcBOY = 0d,
            [ExcelArgument( "Optional.  Employer contribution annual limit. Defaults to unlimited." )]
            object erContributionAnnualLimitArg = null,
            [ExcelArgument( "Optional.  Is this retirement year?" )]
            object isRetirementArg = null,
            [ExcelArgument( "Optional.  Frequency of match in a year." )]
            int matchFreq = 0,
            [ExcelArgument( "Optional.  Frequency of ER Contribution in a year." )]
            int erContFreq = 0,
            [ExcelArgument( "Optional.  Employee Pretax/Roth & Catchup Contributions is based on limited pay." )]
            object pretaxRothPayIsLimitedArg = null,
            [ExcelArgument( "Optional.  Use mid point contributions timing calculation method." )]
            object midPointContributionArg = null,
            [ExcelArgument( "Optional.  Don't apply IRS limit." )]
            object noLimitArg = null,
            [ExcelArgument( "Optional.  Pretax auto increase timing (month): Enter 4 if increase happens on 4/1." )]
            int increaseMonth = 0,
            [ExcelArgument( "Optional.  Pretax auto increase frequency per year." )]
            int increaseFreq = 0,
            [ExcelArgument( "Optional.  Pretax auto increase percentage." )]
            double increasePct = 0,
            [ExcelArgument( "Optional.  Pretax maximum rate." )]
            double maxRate = 0d,
		[ExcelArgument( "Optional.  Pay Limit." )]
		double limitPay = 0d,
		[ExcelArgument( "Optional.  Pretax limit." )]
		double limitPretax = 0d,
		[ExcelArgument( "Optional.  Contribution limit." )]
		double limitContribution = 0d,
		[ExcelArgument( "Optional.  Overflow to non qualified plan." )]
		bool isOverflowToNonQual = false )

Here is where both the intellisense and the Function wizard stop (in the middle of pretaxFlatPerPayPeriod):

<img width="1061" alt="dna" src="https://cloud.githubusercontent.com/assets/6237247/16382708/935f270c-3c47-11e6-88a1-69cba9cd5df8.png">

![excel](https://cloud.githubusercontent.com/assets/6237247/16382713/986fb9f0-3c47-11e6-921b-4379d8495c42.png)

And a function with a long description:

[ExcelFunction( Category = "Financial", Description = "A debug version of BTRGetContributions401kDebug function.  Returns employer match / contribution based on match parameters.  When BTRGetMatchAmt throws a #VALUE, you should switch to this method and it will display the actual error message that is being thrown.  See BTRGetContributions401kDebug for description of parameters." )]

Shows up like:

<img width="1051" alt="dna" src="https://cloud.githubusercontent.com/assets/6237247/16382851/249dbb20-3c48-11e6-9586-7c6e2025f484.png">

![excel](https://cloud.githubusercontent.com/assets/6237247/16382877/37939574-3c48-11e6-8263-4fc50012de50.png)

Thanks in advance.

**Comment by Ron-Ldn** [comment]
There is a limit on the total number of chars for the descriptions, I don't remember what it is.
I believe you just hit the limit and there probably is nothing to do. But Govert will now better than me.

**Comment by Ron-Ldn** [comment]
Actually:
https://groups.google.com/forum/#!searchin/exceldna/238/exceldna/u0QpV6HQwBQ/rlS36uLcxnoJ

**Comment by terryaney** [comment]
Right, that is what I was referring to with the original 'by design'.  Didn't know if any possibility to use alternatives to the same limitation the Function Wizard has.  But if same limitations, it is what it is.  Thanks.

**Comment by govert** [comment]
The limitation is not compiled into the .xll, but when the registration info is sent to Excel. A the moment, the .xll add-in provides the same information to IntelliSense as it registers with Excel.
I can think of some workarounds:
  * Make a help file (possibly using ExcelDnaDoc) or https-based documentation. You can then adds lots of extra information for the function. Help links should work in both the function wizard and when hovering over the name in the IntelliSense pop-up.
  * Check whether the side-loaded xml file allows longer strings to be shown in IntelliSense (i believe so). For this you make a MyAddIn.IntelliSense.xml file to match MyAddIn.xll. It's described here: https://github.com/Excel-DNA/IntelliSense/wiki/Usage-Instructions
  * Finally, a future Excel-DNA version could in theory send the untruncated strings to the IntelliSense. That would be a change inside the main Excel-DNA project and not the IntelliSense extension. I'm not so keen on this route, although it should be possible.

**Comment by terryaney** [comment]
So, I tried to use an external file and there is some sort of misconnect.

1)  Here is my code:

<img width="827" alt="dna" src="https://cloud.githubusercontent.com/assets/6237247/16488427/1b7f7740-3e96-11e6-85db-3eb1610622cf.png">

2) Here is my Xml File (and path in the tooltip):

![dna 3](https://cloud.githubusercontent.com/assets/6237247/16488458/482515b6-3e96-11e6-9cb3-d86ef078b800.png)

3) Here is a screen shot of Excel showing the full path of the add-in along with Windows Explorer showing the location/name of the .xml file again.

<img width="752" alt="dna 2" src="https://cloud.githubusercontent.com/assets/6237247/16488503/756dc874-3e96-11e6-9c18-fa80a5b3ef2f.png">

4) And here is the output.  a) No description shown and b) as I've seen mentioned on https://github.com/Excel-DNA/IntelliSense/issues/6#issuecomment-220723648, the ( ) is overlapping in the tooltip:

<img width="252" alt="dna 1" src="https://cloud.githubusercontent.com/assets/6237247/16488530/98bf4c58-3e96-11e6-9e8e-7645eee93414.png">

Let me know if you see anything obvious with my setup that is preventing it from working.  Thanks.

**Comment by govert** [comment]
Your whole setup looks fine. I'll check it again on my side.

On 30 Jun 2016, at 14:58, Terry Aney <notifications@github.com<mailto:notifications@github.com>> wrote:


So, I tried to use an external file and there is some sort of misconnect.

1) Here is my code:

[dna]<https://cloud.githubusercontent.com/assets/6237247/16488427/1b7f7740-3e96-11e6-85db-3eb1610622cf.png>

2) Here is my Xml File (and path in the tooltip):

[dna 3]<https://cloud.githubusercontent.com/assets/6237247/16488458/482515b6-3e96-11e6-9cb3-d86ef078b800.png>

3) Here is a screen shot of Excel showing the full path of the add-in along with Windows Explorer showing the location/name of the .xml file again.

[dna 2]<https://cloud.githubusercontent.com/assets/6237247/16488503/756dc874-3e96-11e6-9c18-fa80a5b3ef2f.png>

4) And here is the output. a) No description shown and b) as I've seen mentioned on #6 (comment)<https://github.com/Excel-DNA/IntelliSense/issues/6#issuecomment-220723648>, the ( ) is overlapping in the tooltip:

[dna 1]<https://cloud.githubusercontent.com/assets/6237247/16488530/98bf4c58-3e96-11e6-9e8e-7645eee93414.png>

Let me know if you see anything obvious with my setup that is preventing it from working. Thanks.

**Comment by terryaney** [comment]
Thanks.  Couple more issues while you are looking.  Let me know if you want me to make more issues.

My plan of attack is this...
1) ExcelFunction, ExcelArgument attributes as my 'documentation' so that they show up in intellisense and function wizard acknowledging the problem for descriptions > 255 in length

2) Post build step to generate intellisense xml file by looking at the attributes of methods using the same documentation (so only documenting in one place).  Assuming this xml file will take precedence over attributes for the *intellisense* only, thus making intellisense support > 255 in length (hopefully) so it works in one place at least.

3) Finally, I'm creating a *.chm file with ExcelDnaDoc to provide additional documentation for functions that need more information or functions with descriptions/parameters hitting the 255 limitation.  I'd hook to this via the HelpTopic attribute.  This is where I'm having problems.

Here is my code:

<img width="824" alt="dna help code" src="https://cloud.githubusercontent.com/assets/6237247/16499449/29d5d232-3ec6-11e6-8316-0e93129fb18c.png">

Here is intellisense (*note that I thought it was documented that a help link would show up in intellisense, if I'm remembering that right, just showing you that it doesn't)

<img width="665" alt="dna help intelli" src="https://cloud.githubusercontent.com/assets/6237247/16499472/49bc3622-3ec6-11e6-9e08-6cff6c207404.png">

Here is function wizard and error message I get when clicking link:

<img width="583" alt="dna help wizard" src="https://cloud.githubusercontent.com/assets/6237247/16499484/5968c388-3ec6-11e6-9d15-c0329d11f805.png">

Finally, here is a little c# snippet launching the help and topic (noting path is in debug folder, so help file is present) showing that indeed the help file and topic is constructed correctly (to my knowledge):

<img width="953" alt="dna help linqpad" src="https://cloud.githubusercontent.com/assets/6237247/16499528/919245d6-3ec6-11e6-8981-bf2bad64a39c.png">

Let me know if you think my ideas of 1-3 will work (only concern I have is xml file taking precedence over the attributes if both are present).

Also, let me know if you see anything wrong with the HelpTopic setup.

Thanks in advance.

**Comment by govert** [comment]
Your plan sounds good. If the external file does not take precedence it would be easy to fix.

For the HelpLink you need to use the TopicId and not the .htm name. (This is an Excel limitation.)
You might wan to check the ExcelDnaDoc project too - it builds the help file form extended attributes, and hooks up the topic ids automatically.

**Comment by terryaney** [comment]
> Finally, I'm creating a *.chm file with ExcelDnaDoc

:) I've been trying everything to get it to pop open, but can't get it.  Will keep playing with it.

**Comment by govert** [comment]
Have you fixed the HelpTopic to be something like `HelpTopic="MyFile.chm!1001"`?
You should also test with `HelpTopic="http://google.com"` which is simpler for a few reasons...

(When we get the xml file to work, we need to check that the .chm path is fixed up, if needed.)

**Comment by govert** [comment]
I see that the .xml file doesn't work right for an Excel-DNA .xll.
I'll figure that out and fix it.

**Comment by terryaney** [comment]
I didn't try !1001.  Changed to try this:

[ExcelFunction( HelpTopic = "BTR.Extensibility.Excel.chm!1001", 

ExcelDnaDoc then generated the following in the *.hpp file:

```
[ALIAS]
Topic1001=BTRCellAddress.htm

[MAP]
#define Topic1001 1001
```

So not sure why it wouldn't work.

**Comment by govert** [comment]
Here's a project that uses ExcelDnaDoc, with the Help link working in the function wizard and IntelliSense: https://dl.dropboxusercontent.com/u/639121/CsHelpTopic.7z

**Comment by terryaney** [comment]
I don't know what happened, but after opening yours and seeing it work, then mine started working ;)  I thought maybe it was a Release vs Debug issue, but I couldn't reproduce anything.  Thanks for all the help.  Look forward to the Xml version working.

**Comment by terryaney** [comment]
Any luck on the Xml file working as the data source?

**Comment by govert** [comment]
I'm afraid you'll have to be a bit more patient - it's taken 3 years to get the IntelliSense to where it is now...

**Comment by terryaney** [comment]
Haha, no problem.  Didn't know the resource availability allocated to this project.

**Comment by govert** [comment]
@terryaney The current release should now give precedence to the function info from the .xml file, given you one way to get the longer IntelliSense descriptions.

For a future Excel-DNA version, I'll try to change the way the registration info is stored internally, so that it will keep and return to IntelliSense the untruncated versions. You can track this issue: https://github.com/Excel-DNA/ExcelDna/issues/85
