### ISSUE TITLE
How to use the integration mode

### ISSUE THREAD

**Issue by airlu210** [Excel-DNA/IntelliSense#22]
Hello,

I'm developping an excel add-in using excel-dna. Fortunately I found your project which exactly meets my need which is to pop argument descriptions. I have downloaded the code and compiled it. However, I don't know how should I integrated into my add-in code. I'm developing the add-in  using C# as well. Do I need to add anything in my code? Could any one give me some instructions?

Btw, I'd like to try IntelliSense as an independent add-in, but I failed to download the .xll file from the release page. Is there anything wrong with the link? Is there any other place that I can download the xll file?

Thanks a lot for your help!

**Comment by govert** [comment]
The latest test release is this: https://github.com/Excel-DNA/IntelliSense/releases/download/v0.1.1-beta1/ExcelDna.IntelliSense.xll 
Is this the link that is not working for you?

The first step is to just load your Excel-DNA based add-in and this ExcelDna.IntelliSense.xll separately, and confirm that the IntelliSense works right. (I presume your C# add-in is built with Excel-DNA, and not as an Automation add-in?) For this to work, you only need the description attributes `[ExcelFunction(Description=...)]` and `[ExcelArgument(Description=...)]` in your functions. So if the descriptions from your Excel-DNA add-in already show in the function wizard (the Function Arguments dialog) then the IntelliSense should work immediately when you load the ExcelDna.IntelliSense.xll add-in.

Once this works perfectly, you can follow the detailed instructions at the bottom of the page here: https://github.com/Excel-DNA/IntelliSense/wiki/Usage-Instructions, under the heading "Integrated display server: ExcelDna.IntelliSense.dll library"

**Comment by airlu210** [comment]
Yes, this is the link that I used and it does not work for me. However, I'm able to download the .zip source code. Maybe I can try the integration mode directly following the instruction. 

However, I still want to try the independent way. Is there another link? Or could you let me know how to build the independent .xll from the source code?

Thanks!

**Comment by govert** [comment]
OK, you can try this link to get the same file: https://dl.dropboxusercontent.com/u/639121/IntelliSense/ExcelDna.IntelliSense.xll

The independent mode add-in is just the (packed) output of the IntelliSense.Host project that you'll find in the source.

**Comment by airlu210** [comment]
Both independent mode and Integrated mode works well with my add-in! Thanks a lot for the help! This tool is really useful for me!
