### ISSUE TITLE
Hardcoded comma

### ISSUE THREAD

**Issue by anzelika-sa** [Excel-DNA/IntelliSense#23]
Hi,

This is great plugin for UDFs, thanx for developing it :)
We tried to use it today with our custom functions and one thing does not work for us - the parameters are separated by comma and our functions parameters are separated by semicolon. Could intellisense use list separator from regional settings and not hardcoded comma? Please refer to the images attached.

Excel version - 2016

![image](https://cloud.githubusercontent.com/assets/20441595/16807606/c4392044-4921-11e6-9450-576ce264bfd8.png)

![image](https://cloud.githubusercontent.com/assets/20441595/16807620/d0488046-4921-11e6-8858-5eaa40366a95.png)

![image](https://cloud.githubusercontent.com/assets/20441595/16807697/20100aea-4922-11e6-9d33-68a39b2b409a.png)

**Comment by govert** [comment]
The separator has already been fixed in the source - d3b0bedea9734d5b5a5fdc94434301424c112483 - I should make a new beta release with the fix in the next few days.

**Comment by govert** [comment]
Please check the latest release for this: https://github.com/Excel-DNA/IntelliSense/releases/tag/v0.1.4-beta2

**Comment by anzelika-sa** [comment]
Thank you, Govert! :)
