### ISSUE TITLE
Cannot select first line cells because shielded by IntelliSense description box

### ISSUE THREAD

**Issue by airlu210** [Excel-DNA/IntelliSense#24]
Part of first line cells cannot be selected because they are shield by the description box of IntelliSense.
I cannot close the description box or drag it to another place.
Is there a way to solve this problem?

**Comment by govert** [comment]
For now, maybe click in the formula edit box above the sheet?

Later we might make the tooltip movable...

**Comment by airlu210** [comment]
I tried to click the formula edit box, but it does not work. Could you let me know when the tooltip movable is available? Thanks!

**Comment by govert** [comment]
@airlu210 The IntelliSense tooltips can now be moved. See the new release https://github.com/Excel-DNA/IntelliSense/releases/tag/v0.1.5-beta3

**Comment by airlu210** [comment]
It works pretty well! Thanks a lot!
