### ISSUE TITLE
Does Execl-DNA/IntelliSense supports Excel 2013 64bit

### ISSUE THREAD

**Issue by airlu210** [Excel-DNA/IntelliSense#32]
Hello,

I've developed an excel add-in using Excel-DNA and IntelliSense. It works pretty fine with Excel 2013 32bit. However, it does not work with Excel 64bit. What I did is using the same dlls and package them with CIAS64.dna and CIAS64.xll. Does any one knows how to run Excel-DNA add-ins with Excel in 64bit and does IntelliSense supports 64bit?

Thanks.

**Comment by govert** [comment]
Both Excel-DNA and the IntelliSense extension support 64-bit Excel, though it's not a configuration I test often so bugs can slip in.

In what way does it 'not work'?
* Error on loading
* No functions are registered
* IntelliSense popups don't appear

Does your basic add-in (without IntelliSense) work on 64-bit?
Does the 64-bit version of IntelliSense in independent mode work (or test the debug build of the IntelliSense-Host project, which exposes some functions, e.g. AddThem.

**Comment by airlu210** [comment]
Hi,
Thanks for the reply! IntelliSense and Excel-DNA works if not packaged in one dll. however it does not work (as the functions cannot be loaded, ribbon does not show up, no IntelliSense popup) if I package it into one single dll. Do you have any idea on this?
However, there's still problem for my add-in. I use NLog to write logs and AMQ to connect to other system. The UDF and IntelliSense works now for 64-bit excel,  however NLog and AMQ does not work. My add-in should write logs by NLog. It works with 32-bit excel, but when I move it to 64-bit, the logs are not written. And I have a funtion to connect to AMQ, it does not work as well. Do you have any idea on this? Although it is not related to IntelliSense. 
Thanks!

**Comment by govert** [comment]
This sounds like an issue particular to your add-in. I suggest we use the Google group for general support discussion (https://groups.google.com/forum/#!forum/exceldna).

First step would be to make small samples that you can post to the public forum which reproduce the issues.
