### ISSUE TITLE
Version testing: 0.1.10  Beta

### ISSUE THREAD

**Issue by nVenticDW** [Excel-DNA/IntelliSense#35]
Version 0.1.10 Beta doesn't appear to start up when using  Excel 32 bit 2010 (there is no IntelliSense active on my machine). Version 0.1.09 Beta works with IntelliSense.     Dan

**Comment by govert** [comment]
I've tried again and everything works on my side.
Can you check the download again? 
Is the size of the ExcelDna.IntelliSense.xll file right on your side (729 KB)?

**Comment by govert** [comment]
This was due to the used range extending past the list of functions, and resolved with check-in 9670ce969412656dc0ff34f1a3daa537fd058c5b
