### ISSUE TITLE
Add square brackets to [optional] arguments

### ISSUE THREAD

**Issue by jeffreyweir** [Excel-DNA/IntelliSense#36]
I'm looking at the VBA functionality, and think it would be good if any args with the Optional keyword get enclosed with square brackets, as with the native UI. By way of example, here's how the intellisense looks for VLOOKUP:
=VLOOKUP(lookup_value,table_array,col_index_num,**[**range_lookup**]**)

**Comment by govert** [comment]
I think you can just put square brackets around your argument names in the IntelliSense sheet or .xml part. They'll then display with the brackets.

Does that work for you?


On 09 Oct 2016, at 07:54, jeffreyweir <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm looking at the VBA functionality, and think it would be good if any args with the Optional keyword get enclosed with square brackets, as with the native UI. By way of example, here's how the intellisense looks for VLOOKUP:
=VLOOKUP(lookup_value,table_array,col_index_num,[range_lookup])

**Comment by jeffreyweir** [comment]
Ah, yes. I misunderstood how the IntelliSense sheet was working behind the scenes - I thought that the args would have to exactly match the syntax of the args in the UDF itself. But now I see it's the placement that is important.

**Comment by jeffreyweir** [comment]
That said, it would be handy if the app put them in automatically...although this is a pretty minor request.

**Comment by govert** [comment]
It has no way of detecting that the arguments from VBA are optional.

On 09 Oct 2016, at 08:48, jeffreyweir <notifications@github.com<mailto:notifications@github.com>> wrote:


That said, it would be handy if the app put them in automatically...although this is a pretty minor request.

**Comment by flutefreak7** [comment]
So its not impossible for the Intellisense stuff to have code insight?

I'm asking because I feel like I've seen Add-Ins before that augment the VBA Editor or operate on VBA code somehow.  I understand that interacting with a live function through COM is very different from seeing a module full of source code, but I'm curious if being able to parse VBA source code could open other possibilities like detecting optional arguments, default values, reading function annotations from within structured comments instead of from XML, etc.

**Comment by govert** [comment]
@flutefreak7 Certainly it would be possible to parse the VBA source code and generate the IntelliSense info automatically, in the way you describe. It's not work I'm likely to take on myself (i'm focused on the .NET world) but I'd be happy to help anyone giving it a try.
I'm not sure the benefit is very large, though. Whether you made a worksheet with all the descriptions in, or put them into comments in the code, doesn't seem to make a big difference.
I guess I'd rather encourage and help people to move to VB.NET and Visual Studio for their Excel stuff.

**Comment by flutefreak7** [comment]
Thanks! I understand your motivation to get folks over to .NET. I work in an Engineering environment where VBA is widely used to quickly code up engineering / science functions and Macro-enabled Spreadsheets are more easily shareable via E-mail than an add-in (our Outlook blocks xll apparently). I think the hurdles to VB.NET are worth it, but most of my non-programmer colleagues are a tough audience. Maybe easier to implement UDF Intellisense would change some minds?

**Comment by govert** [comment]
@flutefreak7 Well, I know lots of people will keep using VBA for a long time, So I was happy to make the IntelliSense add-in work with VBA functions too. I'm not sure how many people will use it...

But first I nee to figure out how to fix the Excel 2016 (November update) issue, where the Excel update has broken the IntelliSense somehow.
