### ISSUE TITLE
add square brackets

### ISSUE THREAD

**Issue by nVenticDW** [Excel-DNA/IntelliSense#38]
The issue isn't quite closed with square brackets.  I have optional arguements and one just puts square brackets in the "_IntelliSense_" worksheet for instance. I checked that it works and found, however, that if the last paramter is optional then the ] and ) are somehow written over each other. With standard excel this doesn't happen (see vlookup), I attach a snip of a screen shot.
![intellisensesquare brackets](https://cloud.githubusercontent.com/assets/20855083/19218538/d3c1d9b4-8dfc-11e6-8ce8-6ca64643ed29.PNG)

**Comment by govert** [comment]
Yes - that looks like a bug in the formatting.

I'll only be able to have a look in two weeks time, but it should be easy to fix.
You might try, and send a pull request...


On 09 Oct 2016, at 15:51, nVenticDW <notifications@github.com<mailto:notifications@github.com>> wrote:


The issue isn't quite closed with square brackets. I have optional arguements and one just puts square brackets in the "IntelliSense" worksheet for instance. I checked that it works and found, however, that if the last paramter is optional then the ] and ) are somehow written over each other. With standard excel this doesn't happen (see vlookup), I attach a snip of a screen shot.
[intellisensesquare brackets]<https://cloud.githubusercontent.com/assets/20855083/19218538/d3c1d9b4-8dfc-11e6-8ce8-6ca64643ed29.PNG>

**Comment by nVenticDW** [comment]
There is an easy workaround in the meantime:
Add  a blank at the end of every "]" in the _IntelliSense_ Worksheet, when-ever  (and only when-ever) the optional parameter is the last parameter.  This however, if left as it is needs, documentation. As you say Govert, it should be easy to fix in the code.

**Comment by govert** [comment]
@nVenticDW  I've had a look at the current test release - v 0.1.11 - and the formatting for arguments with brackets seems right. I think there were some changes in v 0.1.10.
What version did you check with?
