### ISSUE TITLE
LPenHelper returns previous formula when editing cell

### ISSUE THREAD

**Issue by Ron-Ldn** [Excel-DNA/IntelliSense#4]
If I enter "=AddThem(," then the call to LPenHelper in XlCall.GetFormulaEditPrefix returns "=AddThem(".
Then if I delete the comma, LPenHelper returns "=AddThem(,".

In consequence, the form highlights the wrong argument. 
This doesn't happen when the formula is edited from the formula bar.

**Comment by govert** [comment]
I still get this with Excel 2013. Under Excel 2013 (possibly with Windows 8+) there is support for another UI Automation text pattern. If this works better than the PenHelper, it would be nice to use where available. I'd think this a lower priority to work on, though.

**Comment by Ron-Ldn** [comment]
I don't observe this bug anymore, since my latest changes.
I can't tell whether this is a coincidence. Let's keep an eye on this.

**Comment by Ron-Ldn** [comment]
I think we can close that one as well. It works fine on my Excel 2010.
