### ISSUE TITLE
IntelliSense has 1 char lag

### ISSUE THREAD

**Issue by amibar** [Excel-DNA/IntelliSense#46]
I tested the IntelliSense tag v.1.0.3 on Excel 2016 (Office 365 Business x64) and it fixes the hang we had in issue https://github.com/Excel-DNA/IntelliSense/issues/42.

When I use the new version of the IntelliSense i have a 1 char lag in the tools tips.

For example, let's say I am typing the following chars . Each step contains the text I already typed.

1. =AddThem
2. =AddThem(
3. =AddThem(1
4. =AddThem(1,
5. =AddThem(1,2

After step 2 the tool tip doesn't appear at all, it appear after step 3
After step 4 the second arguments tools tip doesn't appear, it appear after step 5

It look like the tools tip looks at the previous text of the formula and not the current one.

**Comment by govert** [comment]
I can reproduce this on a new add-in with the IntelliSense release, but not when debugging. The debug version has lots of tracing, so there may be some timing issue...

**Comment by amibar** [comment]
@govert, just checked 1.0.6 and it solved this issue, thanks.

**Comment by hell-racer** [comment]
It seems like I'm having the same issue, but it appears when I click inside the text. In the VS's output windows it prints previous formula prefix (the one that was before the FormulaEditStateChanged event.

**Comment by govert** [comment]
@hell-racer I've opened issue #60 to track the problem you describe, which is a bit different to the one originally described.
