### ISSUE TITLE
Is Excel 2007 supported?

### ISSUE THREAD

**Issue by johnnyontheweb** [Excel-DNA/IntelliSense#50]
In Excel 2007, IntelliSense does not show anything (and makes no errors, fortunately).
Is it supported in 2007 version or I have to set something? thanks

**Comment by govert** [comment]
@johnnyontheweb No - I don't expect the IntelliSense to work on Excel 2007. I don't think there are fundamental technical constraints, but I don't have a development environment in place or any incentive to look at Excel 2007.

**Comment by johnnyontheweb** [comment]
Thanks for the reply, I don't have any incentive me neither, but I usually develop with office 2007 to have the maximum compatibility. That's ok, no problem.
