### ISSUE TITLE
Double-clicking the tooltip makes it flicker

### ISSUE THREAD

**Issue by hell-racer** [Excel-DNA/IntelliSense#53]
1. Start editing a custom formula (in-cell or formula edit bar) until tooltip is displayed.
2. Click the tooltip - nothing happens (this is correct)
3. Double-click the tooltip - it flickers. I think it is not supposed to.

**Comment by govert** [comment]
I can reproduce this - no idea why it happens though.

**Comment by hell-racer** [comment]
That's because WndProc in TooltipForm doesn't handle WM_LBUTTONDBLCLK. I've tried to fix (just two lines of code) and it works correctly on my machine. I'm not sure if there are no any side-effects, didn't notice anything bad so far though. I think I can try to create a pull request, but I'm just not very familiar with GitHub :).

**Comment by govert** [comment]
Oh great! You can create a pull request, or just post some details here if that's easier for you.

**Comment by hell-racer** [comment]
Fixed with #54
