### ISSUE TITLE
LoaderLock

### ISSUE THREAD

**Issue by jimfoye** [Excel-DNA/IntelliSense#63]
I get this error now when I load my add-in and call IntelliSenseServer.Register(). I notice there are some comments in the code referencing this possibility. Anything I need to do?

Meanwhile, it appears to work fine on an employee's machine. Though we did notice that the tooltip does not always appear as expected right below the formula bar, but instead likes to move around the Excel workspace.

**Comment by govert** [comment]
You can safely ignore / switch iff the LoaderLock debugging assistant.

For the position not being right, please open a separate issue and some instructions to reproduce - not a problem I'm aware of before.

On 11 Jun 2018, at 22:51, Jim Foye <notifications@github.com<mailto:notifications@github.com>> wrote:


I get this error now when I load my add-in and call IntelliSenseServer.Register(). I notice there are some comments in the code referencing this possibility. Anything I need to do?

Meanwhile, it appears work fine on an employee's machine. Though we did notice that the tooltip does not always appear as expected right below the formula bar, but instead likes to move around the Excel workspace.

**Comment by jimfoye** [comment]
@govert On the positioning, I think it was probably a false alarm, we didn't realize that the tooltip will appear next to a cell when edting inside the cell, instead of the formula bar. Thanks.
