### ISSUE TITLE
Fix up multi-line descriptions

### ISSUE THREAD

**Issue by govert** [Excel-DNA/IntelliSense#69]

**Comment by gmichaud** [comment]
Before I file a duplicate issue, could you confirm if this issue is about what can be seen on that screenshot: 
<img width="803" alt="long description" src="https://user-images.githubusercontent.com/9433888/43356846-35111bea-9246-11e8-8a41-a90f8edbc0f6.png">

**Comment by govert** [comment]
I'm not sure - the layout looks like it is not the current version. 

I think you should post the C# signature and attributes (or the xml fragment) with the full descriptions and I can check from there.

**Comment by gmichaud** [comment]
I was using 1.0.9 and upgraded to 1.1.0 to confirm the issue is still happening. I also turned off high-DPI mode to verify it has anything to do with that and it doesn't look related. Here's my C# signature:

        [ExcelFunction("Calculates the original budgeted amount of one or more project(s) and task(s).", Name = "PROJECTBUDGETAMOUNT")]
        public static object ProjectBudgetAmount(
          [ExcelArgument("Name of the Acumatica connection as configured in the connection manager.", Name = "Connection")] string connectionName,
          [ExcelArgument("The project(s) to include. Multiple projects can be included by separating them with a semicolumn (;), by using a range (START:END) format, or excluded by prefixing with minus (-).", Name = "Project")] string project,
          [ExcelArgument("The task(s) to include. Multiple tasks can be included by separating them with a semicolumn (;), by using a range (START:END) format, or excluded by prefixing with minus (-).", Name = "Task")] string task,
          [ExcelArgument("The account group(s) to include. Multiple account groups can be included by separating them with a semicolumn (;), by using a range (START:END) format, or excluded by prefixing with minus (-).", Name = "AccountGroup")] string accountGroup,
          [ExcelArgument("The cost code(s) to include. Multiple cost codes can be included by separating them with a semicolumn (;), by using a range (START:END) format, or excluded by prefixing with minus (-).", Name = "CostCode")] string costCode,
          [ExcelArgument("The inventory item(s) to include. Multiple inventory items can be included by separating them with a semicolumn (;), by using a range (START:END) format, or excluded by prefixing with minus (-).", Name = "InventoryItem")] string inventoryItem)
        {
            //Body here
        }

**Comment by wh1t3cAt1k** [comment]
We were able to fix the issue posted above by @gmichaud , by tweaking `ToolTipForm.GetRunParts` method to also split on space:

![image](https://user-images.githubusercontent.com/5159662/82905163-30aab680-9f6c-11ea-8a03-759a1e761ff9.png)
