### ISSUE TITLE
InvalidCastException thrown if LoadFromBytes or Packed set true

### ISSUE THREAD

**Issue by bevanweiss** [Excel-DNA/IntelliSense#9]
When trying to use either LoadFromBytes or Packed attributes on my custom dll then I get the following exception thrown on line 69 of CrossAppDomainSingleton.cs
An exception of type 'System.InvalidCastException' occurred in ExcelDna.IntelliSense but was not handled in user code
Additional information: Unable to cast transparent proxy to type 'ExcelDna.IntelliSense.IntelliSenseDisplay'.

This is under Windows 7 32-bit with Excel 2013.

My googleage suggests this is related to an assembly being loaded from an incorrect location/context.
http://weblog.west-wind.com/posts/2012/Jan/13/Unable-to-cast-transparent-proxy-to-type-type
http://stackoverflow.com/questions/1437831/appdomain-createinstancefromandunwrap-unable-to-cast-transparent-proxy

If I remove these attributes on both the ExcelDNA.Intellisense.dll and my custom dll (in the .dna file) then it does indeed work as brilliantly as expected (although provides a different exception when exiting Excel, which I'll file separately).

**Comment by govert** [comment]
I don't expect this problem with current versions - the cross-AppDomain handling has been removed.
Please re-open if I'm mistaken.
