### ISSUE TITLE
Support for non-ExcelDNA xll?

### ISSUE THREAD

**Issue by abc983ft** [Excel-DNA/IntelliSense#93]
Hello, I see that you currently support adding intellisense for .NET xlls built using ExcelDNA but I was wondering if you also support xll’s built using other vendors such as AddinExpress which allows for the coding logic to be in C++ which is not possible in ExcelDna.

Is such functionality currently possible (in which case documentation should be updated) or could you please consider this as possible feature to add in the future?

**Comment by augustoproiete** [comment]
@abc983ft It's possible to use `ExcelDna.IntelliSense` with any workbook, `.xlam` add-in or `.xll` add-in (native or managed) as long as you provide an `.xml` file alongside the add-in, that describes the functions and the IntelliSense information to be displayed:

Documentation:
https://github.com/Excel-DNA/IntelliSense/wiki/Usage-Instructions#external-intellisensexml-file
