### ISSUE TITLE
IntelliSenseServerControl_{UUID} macro always fails

### ISSUE THREAD

**Issue by tonyroberts** [Excel-DNA/IntelliSense#99]
Calling the IntelliSenseServerControl_{UUID} macro fails with Error 2015 (#VALUE).

It looks like this is due to a change in 2aa6549831e55efd8291aed6a78bb2b36bbd9d6e where the method IntelliSenseServerControl was changed from public to private.

I'm not sure if exposing private methods as macros should work or not? However, when calling the macro the following C# exception is raised:

```"Attempt by method 'WrapperType.Wrapped_f2_IntelliSenseServerControl(System.Object)' to access method 'ExcelDna.IntelliSense.IntelliSenseServer.IntelliSenseServerControl(System.Object)' failed."```

Changing the IntelliSenseServerControl  method back to public fixes it.

**Comment by govert** [comment]
Thank you for reporting this @tonyroberts . I hope it's fixed now in version 1.4.1. Please let me know if it is not, or if you run into any other issues.

**Comment by tonyroberts** [comment]
Thanks @govert. I just tested it and it's working perfectly! :)
